# Dockerfile for a Node.js Web API application
FROM node:18-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the application source code (game.js)
COPY srcfile .

# Document which port the application inside the container is listening on.
# The Node.js server is listening on 3000.
EXPOSE 3000

# Command to run the server when the container starts
CMD ["node", "srcfile"]
